# Generated by Django 5.0.14 on 2026-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='public/profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Desayuno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='public/profile/')),
            ],
            options={
                'db_table': 'desayunos',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='public/profile/')),
            ],
            options={
                'db_table': 'entradas',
            },
        ),
        migrations.CreateModel(
            name='PlatoFuerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='public/profile/')),
            ],
            options={
                'db_table': 'platosfuertes',
            },
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='public/profile/')),
            ],
            options={
                'db_table': 'postres',
            },
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precioCopa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precioBotella', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='public/profile/')),
            ],
            options={
                'db_table': 'vinos',
            },
        ),
    ]
